### ISSUE TITLE
Data.HashMap.Base.(!): key not found

### ISSUE THREAD

**Issue by pbrisbin** [LeapYear/hpc-lcov#13]
## Describe the bug

See Title.

## Steps to Reproduce

Over in my [bugsnag-haskell](https://github.com/pbrisbin/bugsnag-haskell) project,

```console
% stack build --coverage --flag bugsnag-haskell:examples --fast --pedantic --test
{ passing test output elided }

bugsnag-haskell> Test suite spec passed
{ successful generation output ellided }

The unified report is available at /home/patrick/code/pbrisbin/bugsnag-haskell/.stack-work/install/x86_64-linux/02d47e96fd017a924798f196a44899a9f0f32f4a8b3e611697067747477e1c2c/8.6.5/hpc/combined/all/hpc_index.html

An index of the generated HTML coverage reports is available at /home/patrick/code/pbrisbin/bugsnag-haskell/.stack-work/install/x86_64-linux/02d47e96fd017a924798f196a44899a9f0f32f4a8b3e611697067747477e1c2c/8.6.5/hpc/index.html
% stack exec hpc-lcov
hpc-lcov: Data.HashMap.Base.(!): key not found
CallStack (from HasCallStack):
  error, called at ./Data/HashMap/Base.hs:631:16 in unordered-containers-0.2.10.0-LgoTL3wbBEY5bZIDJiyxW4:Data.HashMap.Base
```

I know the coverage data is good, because the HTML appears valid:

![](https://files.pbrisbin.com/screenshots/screenshot.324543.png)

## Expected behavior

It should not panic. It should report a meaningful error (if this is operator error) or generate an `lcov.info` successfully (if not).

## Environment

* Stack version: `Version 2.1.3, Git revision 636e3a759d51127df2b62f90772def126cdf6d1f (7735 commits) x86_64 hpack-0.31.2`
* Library version: `1.0.0`

## Sidenote

Nice package! I considered this approach (using lcov as intermediate) when I wrote [cc-coverage](https://github.com/pbrisbin/hs-cc-coverage). I forget why I decided not to :thinking:. Anyway, super excited to stop maintaining that package and use this instead!

**Comment by brandon-leapyear** [comment]
Hi @pbrisbin! So sorry for not getting to this sooner. For some reason, I didn't get any notifications when you submitted this issue.

Is this still an issue for you? The only instance I'm seeing of `!` is here: https://github.com/LeapYear/hpc-lcov/blob/master/exe/Main.hs#L172. Does your `stack.yaml` file not have any `packages` key?

**Comment by brandon-leapyear** [comment]
Oh I see. TIL that `packages` is optional and defaults to
```yaml
packages:
- .
```
I'll go ahead and make a fix

**Comment by pbrisbin** [comment]
Thanks for the quick (once you heard about it anyway) fix!
